name: Update Remote Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: |
        curl https://server.littleyang.com.cn/ascas/check -H "Authorization: Bearer ${{ secrets.TOKEN }}" -sN | bash
    - name: Update
      run: |
        curl https://server.littleyang.com.cn/ascas -H "Authorization: Bearer ${{ secrets.TOKEN }}" -sN
