name: check & deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: |
        curl https://server.littleyang.com.cn/ascas/check -H "Authorization: Bearer ${{ secrets.TOKEN }}" -sN | bash
        
  deploy:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      run: |
        curl https://server.littleyang.com.cn/ascas/deploy -H "Authorization: Bearer ${{ secrets.TOKEN }}" -sN
