#pragma

#include <string>

const std::string config_json = std::string("{\n"
                                            "    \"server.listenHost\": \"0.0.0.0\",\n"
                                            "    \"server.listenPort\": 8080,\n"
                                            "    \"server.enableSSL\": false,\n"
                                            "    \"server.httpsCacert\": \"cert.pem\",\n"
                                            "    \"server.httpsPrivkey\": \"privkey.pem\",\n"
                                            "    \"server.threadNumber\": 8,\n"
                                            "\n"
                                            "    \"log.level\": \"LOG_LEVEL_INFO\",\n"
                                            "    \"log.target\": [ \"LOG_TARGET_FILE\", \"LOG_TARGET_CONSOLE\" ],\n"
                                            "    \"log.file\": \"ascas-backend.log\",\n"
                                            "\n"
                                            "    \"mysql.host\": \"127.0.0.1\",\n"
                                            "    \"mysql.port\": 3306,\n"
                                            "    \"mysql.user\": \"root\",\n"
                                            "    \"mysql.passwd\": \"\",\n"
                                            "    \"mysql.database\": \"ascas\",\n"
                                            "\n"
                                            "    \"users.sessionExpireTime\": 30,\n"
                                            "    \"users.verifyExpireTime\": 1,\n"
                                            "    \"users.resetExpireTime\": 1,\n"
                                            "\n"
                                            "    \"teams.inviteExpireTime\": 24,\n"
                                            "\n"
                                            "    \"smtp.host\": \"smtp.example.com\",\n"
                                            "    \"smtp.port\": 465,\n"
                                            "    \"smtp.ssl\": true,\n"
                                            "    \"smtp.tls\": false,\n"
                                            "    \"smtp.user\": \"testuser@example.com\",\n"
                                            "    \"smtp.passwd\": \"password\",\n"
                                            "\n"
                                            "    \"images.maxSize\": 512,\n"
                                            "    \"avatars.maxSize\": 128\n"
                                            "}", 852);
