#pragma

#include <string>

const std::string reset_html = std::string("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                                           "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                                           "    <head>\n"
                                           "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                                           "        <title>ASCAS \xE5\xAF\x86\xE7\xA0\x81\xE9\x87\x8D\xE7\xBD\xAE</title>\n"
                                           "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n"
                                           "    </head>\n"
                                           "    <body style=\"margin: 0px;\">\n"
                                           "        <table class=\"container\" style=\"background-color: #f8f8f9; width: 100%; font-family: Noto Sans SC\" cellpadding=\"0\" cellspacing=\"0\">\n"
                                           "            <tbody>\n"
                                           "                <tr><td>\n"
                                           "                    <table class=\"row1\" style=\"width: 100%; background-color: #fff; height: 64px;\" cellpadding=\"0\" cellspacing=\"0\">\n"
                                           "                        <tbody>\n"
                                           "                            <tr>\n"
                                           "                                <td style=\"padding: 0px 20px;\">\n"
                                           "                                    <div style=\"text-align: center; margin: 0; height: 48px; padding: 8px;\">\n"
                                           "                                        <img src=\"https://ascas.littleyang.com.cn/favicon.ico\" style=\"width: 48px; height: 48px; vertical-align: middle;\" alt=\"logo\"/>\n"
                                           "                                        <span style=\"font-size: 24px; font-weight: 500; vertical-align: middle;\">ASCAS</span>\n"
                                           "                                    </div>\n"
                                           "                                </td>\n"
                                           "                            </tr>\n"
                                           "                        </tbody>\n"
                                           "                    </table>\n"
                                           "                </td></tr>\n"
                                           "                <tr style=\"height: 48px;\"><td></td></tr>\n"
                                           "                <tr><td>\n"
                                           "                    <table align=\"center\" class=\"row2\" style=\"max-width: 600px; width: 100%; height: 200px; background-color: #fff;\" cellpadding=\"0\" cellspacing=\"0\">\n"
                                           "                        <tbody>\n"
                                           "                            <tr style=\"height: 32px;\"><td></td></tr>\n"
                                           "                            <tr>\n"
                                           "                                <td>\n"
                                           "                                    <p style=\"text-align: center\"><img src=\"https://ascas.littleyang.com.cn/favicon.ico\" style=\"width: 128px; height: 128px;\" alt=\"logo\"/></p>\n"
                                           "                                    <h1 style=\"text-align: center; color: #333333;\">ASCAS \xE5\xAF\x86\xE7\xA0\x81\xE9\x87\x8D\xE7\xBD\xAE</h1>\n"
                                           "                                    <p style=\"margin-left: 20px; margin-bottom: 0px; color: #555555;\">\xE5\xB0\x8A\xE6\x95\xAC\xE7\x9A\x84 {{ name }} \xE7\x94\xA8\xE6\x88\xB7\xEF\xBC\x9A</p>\n"
                                           "                                    <p style=\"margin-left: 20px; margin-top: 0px; color: #555555;\">\xE6\x88\x91\xE4\xBB\xAC\xE5\xB7\xB2\xE6\x94\xB6\xE5\x88\xB0\xE6\x82\xA8\xE7\x9A\x84\xE5\xAF\x86\xE7\xA0\x81\xE9\x87\x8D\xE7\xBD\xAE\xE8\xAF\xB7\xE6\xB1\x82\xEF\xBC\x8C\xE8\xAF\xB7\xE7\x82\xB9\xE5\x87\xBB\xE4\xBB\xA5\xE4\xB8\x8B\xE6\x8C\x89\xE9\x92\xAE\xE5\xAE\x8C\xE6\x88\x90\xE5\xAF\x86\xE7\xA0\x81\xE9\x87\x8D\xE7\xBD\xAE\xEF\xBC\x9A</p>\n"
                                           "                                    <div style=\"display: block; width: 100%\"><a href=\"{{ link }}\" style=\"text-align: center; display: block; margin-left: 20px; margin-right: 20px; padding: 10px 20px; background-color: #007bff; color: #ffffff; text-decoration: none; border-radius: 5px;\">\xE9\x87\x8D\xE7\xBD\xAE\xE5\xAF\x86\xE7\xA0\x81</a></div>\n"
                                           "                                    <p style=\"margin-left: 20px; margin-bottom: 0px; color: #555555;\">\xE6\x97\xA0\xE6\xB3\x95\xE6\xAD\xA3\xE5\xB8\xB8\xE6\x98\xBE\xE7\xA4\xBA\xEF\xBC\x9F\xE8\xAF\xB7\xE5\xA4\x8D\xE5\x88\xB6\xE4\xBB\xA5\xE4\xB8\x8B\xE9\x93\xBE\xE6\x8E\xA5\xE8\x87\xB3\xE6\xB5\x8F\xE8\xA7\x88\xE5\x99\xA8\xE6\x89\x93\xE5\xBC\x80\xEF\xBC\x9A</p>\n"
                                           "                                    <a style=\"margin-left: 20px; color: #007bff; display: inline-block; width: calc(100% - 40px); overflow: hidden; white-space: nowrap; text-overflow: ellipsis;\" href=\"{{ link }}\">\xE5\xAF\x86\xE7\xA0\x81\xE9\x87\x8D\xE7\xBD\xAE\xE9\x93\xBE\xE6\x8E\xA5</a>\n"
                                           "                                    <p style=\"margin-left: 20px; margin-bottom: 0px; color: #555555; font-weight: 800;\">\xE5\xA6\x82\xE9\x9D\x9E\xE6\x9C\xAC\xE4\xBA\xBA\xE6\x93\x8D\xE4\xBD\x9C\xEF\xBC\x8C\xE8\xAF\xB7\xE5\xBF\xBD\xE7\x95\xA5\xE3\x80\x82</p>\n"
                                           "                                </td>\n"
                                           "                            </tr>\n"
                                           "                            <tr style=\"height: 32px;\"><td></td></tr>\n"
                                           "                            <tr><td>\n"
                                           "                                <p style=\"margin-left: 20px; margin-bottom: 0px; color: #555555;\">\xE6\xAD\xA4\xE8\x87\xB4</p>\n"
                                           "                                <p style=\"margin-left: 20px; margin-top: 5px; color: #555555; font-weight: 800;\">ASCAS \xE5\x9B\xA2\xE9\x98\x9F</p>\n"
                                           "                            </td></tr>\n"
                                           "                            <tr style=\"height: 32px;\"><td></td></tr>\n"
                                           "                        </tbody>\n"
                                           "                    </table>\n"
                                           "                </td></tr>\n"
                                           "                <tr style=\"height: 48px;\"><td></td></tr>\n"
                                           "            </tbody>\n"
                                           "        </table>\n"
                                           "    </body>\n"
                                           "</html>", 4102);
